[[guests]]
name = "Christine und Stephan"
attending.Christine = ["afternoon", "dinner", "hike"]
attending.Stephan = ["afternoon", "dinner"]
is-invited-by-paper = true
is-invited-to-hike = true
[[guests]]
name = "Marina und Timo"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Marina = ["afternoon", "dinner", "hike"]
attending.Timo = ["afternoon", "dinner", "hike"]
[[guests]]
name = "Martin und Andrea"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Martin = ["afternoon", "dinner"]
attending.Andrea = ["afternoon", "dinner"]
[[guests]]
name = "Manfred und Margit"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Manfred = ["afternoon", "dinner"]
attending.Margit = ["afternoon", "dinner"]
[[guests]]
name = "Arno"
attending = ["afternoon", "dinner", "hike"]
is-invited-by-paper = true
is-invited-to-hike = true
[[guests]]
name = "Islam"
attending = ["afternoon", "dinner"]
is-invited-by-paper = true
is-invited-to-hike = true
[[guests]]
name = "Mario und Celina"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Mario = ["afternoon", "dinner", "hike"]
attending.Celina = ["afternoon", "dinner", "hike"]
[[guests]]
name = "Visu und Nina"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Visu = ["afternoon", "dinner"]
attending.Nina = ["afternoon", "dinner"]
[[guests]]
name = "David"
is-invited-by-paper = true
is-invited-to-hike = true
attending.David = ["afternoon", "dinner", "hike"]
[[guests]]
name = "Lea"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Lea = ["afternoon","dinner","hike"]
[[guests]]
name = "Fabian und Anja"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Fabian = ["afternoon", "dinner"]
attending.Anja = ["afternoon", "dinner"]
[[guests]]
name = "Remo"
attending = ["afternoon", "dinner", "hike"]
is-invited-by-paper = true
is-invited-to-hike = true
[[guests]]
name = "Flavio"
attending = ["afternoon", "dinner"]
is-invited-by-paper = true
is-invited-to-hike = true
[[guests]]
name = "Lukas"
is-invited-by-paper = false
is-invited-to-hike = true
attending = ["afternoon", "dinner", "hike"]
[[guests]]
name = "Janosch"
is-invited-by-paper = true
is-invited-to-hike = true
attending = ["hike"]
[[guests]]
name = "Aaron"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Aaron = ["hike"]
[[guests]]
name = "Simon"
is-invited-by-paper = true
is-invited-to-hike = false
attending = ["afternoon", "dinner"]
# Petra
[[guests]]
name = "Regula und JÃ¼rg"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Regula = ["afternoon", "dinner", "hike"]
attending."JÃ¼rg" = ["afternoon", "dinner", "hike"]
[[guests]]
name = "Grossmami"
is-invited-by-paper = true
is-invited-to-hike = false
attending = []
[[guests]]
name = "Nick, Emma, Lina und Kelian"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Nick = ["afternoon", "dinner", "hike"]
attending.Emma = ["afternoon", "dinner", "hike"]
attending.Lina = []
attending.Kelian = []
[[guests]]
name = "Kaj und Nadine"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Kaj = ["afternoon", "dinner", "hike"]
attending.Nadine = ["afternoon", "dinner"]
[[guests]]
name = "Jan und Prisca"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Jan = ["afternoon", "dinner"]
attending.Prisca = ["afternoon", "dinner"]
[[guests]]
name="Katharina, Irina und Xenia"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Katharina = ["afternoon", "dinner", "hike"]
attending.Irina = []
attending.Xenia = []
[[guests]]
name="Vera und Lukas"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Vera = ["afternoon", "dinner"]
attending.Lukas = ["afternoon", "dinner"]
[[guests]]
name="Philipp und Irene"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Philipp = ["afternoon", "dinner"]
attending.Irene = ["afternoon", "dinner"]
[[guests]]
name="Davia und Jonathan"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Davia = ["afternoon", "dinner"]
attending.Jonathan = ["afternoon", "dinner"]
[[guests]]
name="Jorim und Joana"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Jorim = ["afternoon", "dinner"]
attending.Joana = ["afternoon", "dinner"]
[[guests]]
name="Kurt und Brigitte"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Kurt = ["afternoon", "dinner"]
attending.Brigitte = ["afternoon", "dinner"]
[[guests]]
name="Nathanja und Nathanael"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Nathanja = ["afternoon"]
attending.Nathanael = []
[[guests]]
name="Salome und Patrick"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Salome = ["afternoon", "dinner"]
attending.Patrick = ["afternoon", "dinner"]
[[guests]]
name="Tabea"
is-invited-by-paper = true
is-invited-to-hike = false
attending = []
[[guests]]
name="Christian"
is-invited-by-paper = true
is-invited-to-hike = false
attending = []
[[guests]]
name="Adina und Roman"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Adina = ["afternoon", "dinner", "hike"]
attending.Roman = ["afternoon", "dinner", "hike"]
[[guests]]
name="Heiner und Surat"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Heiner = ["afternoon", "dinner"]
attending.Surat = ["afternoon", "dinner"]
[[guests]]
name="Kaspar und Heidi"
is-invited-by-paper = true
is-invited-to-hike = false
attending.Kaspar = ["afternoon", "dinner"]
attending.Heidi = ["afternoon", "dinner"]
[[guests]]
name="Barbara, Res, Maik und Neil"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Barbara = ["afternoon", "dinner"]
attending.Res = ["afternoon", "dinner"]
attending.Maik = ["afternoon", "dinner"]
attending.Neil = ["afternoon", "dinner"]
[[guests]]
name="Raneem und David"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Raneem = ["afternoon", "dinner"]
attending.David = ["afternoon", "dinner"]
[[guests]]
name="Mirjam und Jovin"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Mirjam = ["afternoon", "dinner", "hike"]
attending.Jovin = ["afternoon", "dinner"]
[[guests]]
name="Daniel und Gina"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Daniel = ["afternoon", "dinner"]
attending.Gina = ["afternoon", "dinner"]
[[guests]]
name="Jasmine und Marcel"
is-invited-by-paper = true
is-invited-to-hike = true
attending.Jasmine = ["afternoon", "dinner"]
attending.Marcel = ["afternoon", "dinner"]
[[guests]]
name="Camilla"
is-invited-by-paper = true
is-invited-to-hike = true
attending = ["afternoon", "dinner", "hike"]
[[guests]]
name="Turnverein Pflanzschule"
is-invited-by-paper = true
is-invited-to-hike = false
attending = ["afternoon"]
